# OpenAPI version identifier - required for OpenAPI 3.1 domains
openapi: 3.1.0

#######################
# Optional info section
#######################
info:
  version: 1.0.0
  title: Color Correction Control API
  description: API For controlling the color correction on Blackmagic Design products based on DaVinci Resolve Color Corrector

components:
  ####################
  # Common data models
  ####################
  schemas:
    Lift:
      type: object
      properties:
        red:
          type: number
          maximum: 2.0
          minimum: -2.0
          default: 0.0
        green:
          type: number
          maximum: 2.0
          minimum: -2.0
          default: 0.0
        blue:
          type: number
          maximum: 2.0
          minimum: -2.0
          default: 0.0
        luma:
          type: number
          maximum: 2.0
          minimum: -2.0
          default: 0.0
    Gamma:
      type: object
      properties:
        red:
          type: number
          maximum: 4.0
          minimum: -4.0
          default: 0.0
        green:
          type: number
          maximum: 4.0
          minimum: -4.0
          default: 0.0
        blue:
          type: number
          maximum: 4.0
          minimum: -4.0
          default: 0.0
        luma:
          type: number
          maximum: 4.0
          minimum: -4.0
          default: 0.0
    Gain:
      type: object
      properties:
        red:
          type: number
          maximum: 16.0
          minimum: 0.0
          default: 0.0
        green:
          type: number
          maximum: 16.0
          minimum: 0.0
          default: 0.0
        blue:
          type: number
          maximum: 16.0
          minimum: 0.0
          default: 0.0
        luma:
          type: number
          maximum: 16.0
          minimum: 0.0
          default: 0.0
    Offset:
      type: object
      properties:
        red:
          type: number
          maximum: 8.0
          minimum: -8.0
          default: 0.0
        green:
          type: number
          maximum: 8.0
          minimum: -8.0
          default: 0.0
        blue:
          type: number
          maximum: 8.0
          minimum: -8.0
          default: 0.0
        luma:
          type: number
          maximum: 8.0
          minimum: -8.0
          default: 0.0
    Contrast:
      type: object
      properties:
        pivot:
          type: number
          maximum: 1.0
          minimum: 0.0
          default: 0.5
        adjust:
          type: number
          maximum: 2.0
          minimum: 0.0
          default: 1.0
    Color:
      type: object
      properties:
        hue:
          type: number
          maximum: 1.0
          minimum: -1.0
          default: 0.0
        saturation:
          type: number
          maximum: 2.0
          minimum: 0.0
          default: 1.0
    LumaContribution:
      type: object
      properties:
        lumaContribution:
          type: number
          maximum: 1.0
          minimum: 0.0
          default: 1.0

  ####################
  # Common parameters
  ####################
  parameters: {}

  #######################
  # Common request bodies
  #######################
  requestBodies: {}
  
  ####################
  # Common responses
  ####################
  responses: {}

  #########################
  # Common headers
  # (except request headers - they are defined as parameters)
  #########################
  headers: {}

  #######################
  # Common path items
  #######################
  pathitems:
    colorCorrection.lift:
      get:
        operationId: getColorCorrectionLift
        summary: Get color correction lift
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Lift'
      put:
        operationId: putColorCorrectionLift
        summary: Set color correction lift
        requestBody:
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/Lift'
        responses:
          200:
            description: OK
    colorCorrection.gamma:
      get:
        operationId: getColorCorrectionGamma
        summary: Get color correction gamma
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Gamma'
      put:
        operationId: putColorCorrectionGamma
        summary: Set color correction gamma
        requestBody:
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/Gamma'
        responses:
          200:
            description: OK
    colorCorrection.gain:
      get:
        operationId: getColorCorrectionGain
        summary: Get color correction gain
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Gain'
      put:
        operationId: putColorCorrectionGain
        summary: Set color correction gain
        requestBody:
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/Gain'
        responses:
          200:
            description: OK
    colorCorrection.offset:
      get:
        operationId: getColorCorrectionOffset
        summary: Get color correction offset
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Offset'
      put:
        operationId: putColorCorrectionOffset
        summary: Set color correction offset
        requestBody:
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/Offset'
        responses:
          200:
            description: OK
    colorCorrection.contrast:
      get:
        operationId: getColorCorrectionContrast
        summary: Get color correction contrast
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Contrast'
      put:
        operationId: putColorCorrectionContrast
        summary: Set color correction contrast
        requestBody:
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/Contrast'
        responses:
          200:
            description: OK
    colorCorrection.color:
      get:
        operationId: getColorCorrectionColor
        summary: Get color correction color properties
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Color'
      put:
        operationId: putColorCorrectionColor
        summary: Set color correction color properties
        requestBody:
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/Color'
        responses:
          200:
            description: OK
    colorCorrection.lumaContribution:
      get:
        operationId: getColorCorrectionLumaContribution
        summary: Get color correction luma contribution
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/LumaContribution'
      put:
        operationId: putColorCorrectionLumaContribution
        summary: Set color correction luma contribution
        requestBody:
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/LumaContribution'
        responses:
          200:
            description: OK
