# OpenAPI version identifier - required for OpenAPI 3.1 domains
openapi: 3.1.0

#######################
# Optional info section
#######################
info:
  version: 1.0.0
  title: Preset Control API
  description: API For controlling the presets on Blackmagic Design products

components:
  ####################
  # Common data models
  ####################
  schemas:
    presetList:
      type: object
      properties:
        presets:
          type: array
          items:
            type: string
          description: List of the presets on the camera
    postPresetResponse:
      type: object
      properties:
        presetAdded:
          type: string
          description: Name of the preset uploaded
    activePreset:
      type: object
      properties:
        preset:
          type: string

  ####################
  # Common parameters
  ####################
  parameters: {}

  #######################
  # Common request bodies
  #######################
  requestBodies: {}
  
  ####################
  # Common responses
  ####################
  responses: {}

  #########################
  # Common headers
  # (except request headers - they are defined as parameters)
  #########################
  headers: {}

  #######################
  # Common path items
  #######################
  pathitems:
    presets:
      get:
        summary: Get the list of the presets on the camera
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/presetList'
      post:
        summary: Send a preset file to the camera
        requestBody:
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/postPresetResponse'
    presets.active:
      get:
        summary: Get the list of the presets on the camera
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/activePreset'
      put:
        summary: Set the active preset on the camera
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/activePreset'
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  type: string
    presets.{presetName}:
      get:
        summary: Download the preset file
        parameters:
          - in: path
            name: presetName
            description: name of the preset file
            required: true
            schema:
              type: string
        responses:
          200:
            description: OK
            content:
              application/octet-stream:
                schema:
                  type: string
                  format: binary
      put:
        summary: Update a preset on the camera if it exists, if not create a preset and save current state with the presetName
        parameters:
          - in: path
            name: presetName
            description: name of the preset file
            required: true
            schema:
              type: string
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  type: string
      delete:
        summary: Delete a preset from a camera if exists
        parameters:
          - in: path
            name: presetName
            description: name of the preset file
            required: true
            schema:
              type: string
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  type: string
