# OpenAPI version identifier - required for OpenAPI 3.1 domains
openapi: 3.1.0

#######################
# Optional info section
#######################
info:
  version: 1.0.0
  title: Timeline Control API
  description: API for controlling playback timeline.

components:
  ####################
  # Common data models
  ####################
  schemas:
    Timeline:
      type: object
      properties:
        clips:
          type: array
          items:
            type: object
            properties:
              clipUniqueId:
                type: integer
                description: Unique ID used to identify this clip
                example: 1
              frameCount:
                type: integer
                description: Number of frames in this clip on the timeline
                example: 90000
    AddClip:
      oneOf:
        - type: object
          properties:
            clips:
              type: integer
              description: Unique ID used to identify this clip
              example: 1
        - type: object
          properties:
            clips:
              type: array
              items:
                type: integer
                description: Unique ID used to identify this clip
              example: [1, 2, 3]
              
  ####################
  # Common parameters
  ####################
  parameters: {}

  #######################
  # Common request bodies
  #######################
  requestBodies: {}
  
  ####################
  # Common responses
  ####################
  responses: {}

  #########################
  # Common headers
  # (except request headers - they are defined as parameters)
  #########################
  headers: {}

  #######################
  # Common path items
  #######################
  pathitems:
    timelines.0:
      get:
        operationId: getTimelines0
        summary: Get the current playback timeline.
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Timeline'
      delete:
        operationId: deleteTimelines0
        summary: Clear the current playback timeline.
        responses:
          204:
            description: No Content
    timelines.0.add:
      post:
        operationId: postTimelines0Add
        summary: Add a clip to the end of the timeline.
        requestBody:
          description: Clip information to add
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddClip'
        responses:
          204:
            description: No Content


  